# Generated by Django 3.1.7 on 2021-05-20 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('staff', models.BooleanField(default=False)),
                ('superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='item', max_length=200)),
            ],
            options={
                'db_table': 'Items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_supplied', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date supplied')),
                ('quantity', models.PositiveIntegerField(default='0')),
                ('unit_type', models.CharField(default='meters', max_length=20)),
                ('event', models.CharField(default='event', max_length=350)),
                ('item', models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.item')),
            ],
            options={
                'db_table': 'Inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='deadline')),
                ('User', models.ForeignKey(blank=True, db_column='name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event',
                'managed': True,
            },
        ),
    ]
